# dblstreamgen - Generation Configuration for Databricks
# Event schemas and test execution parameters

# Common fields that appear in ALL events
# Customize these for your use case
common_fields:
  player_id:
    type: "int"
    range: [1, 1000000]
  game_id:
    type: "string"
    values: ["game_01", "game_02", "game_03"]

# Event types and their specific fields
event_types:
  # Session start events (30%)
  - event_type_id: "player.session.start"
    weight: 0.30
    avg_payload_kb: 2
    fields:
      session_id:
        type: "uuid"
      device_type:
        type: "string"
        values: ["iOS", "Android", "PC", "Console"]
        weights: [0.35, 0.30, 0.20, 0.15]
      region:
        type: "string"
        values: ["NA", "EU", "APAC", "LATAM"]
        weights: [0.40, 0.30, 0.20, 0.10]
      app_version:
        type: "string"
        values: ["1.0.0", "1.1.0", "1.2.0", "2.0.0"]
  
  # Game action events (65% - most common)
  - event_type_id: "player.action.game_event"
    weight: 0.65
    avg_payload_kb: 3
    fields:
      action_type:
        type: "string"
        values: ["jump", "shoot", "move", "interact", "crouch", "reload"]
        weights: [0.15, 0.25, 0.35, 0.10, 0.10, 0.05]
      x_coordinate:
        type: "float"
        range: [0.0, 1000.0]
      y_coordinate:
        type: "float"
        range: [0.0, 1000.0]
      health:
        type: "int"
        range: [0, 100]
  
  # Purchase events (5% - rare)
  - event_type_id: "player.action.purchase"
    weight: 0.05
    avg_payload_kb: 5
    fields:
      transaction_id:
        type: "uuid"
      item_id:
        type: "int"
        range: [1000, 9999]
      price:
        type: "float"
        range: [0.99, 99.99]
      currency:
        type: "string"
        values: ["USD", "EUR", "GBP"]

# Test execution parameters
test_execution:
  # Base throughput (events per second)
  # Adjust based on your cluster size and requirements
  base_throughput_per_sec: 1000
  
  # Batch size for publishing
  batch_size: 100

